uhawaii-system-its-ti-iam/uh-groupings

ui/api-handshake.js, ui/package.json, ui/src/middleware.ts, ui/tailwind.config.ts
[GROUPINGS-1626](https://uhawaii.atlassian.net/browse/GROUPINGS-1626)
-   Fix middleware.ts bug
-   Fix ESLint error in tailwind.config.ts
=> Create API Handshake

ui/.eslintrc.json, ui/src/app/about/page.tsx, ui/src/components/layout/navbar/Navbar.tsx, ui/src/services/EmailService.ts, ui/src/services/FetchService.ts, ui/tests/app/about/About.test.tsx, ui/tests/services/EmailService.test.ts, ui/tests/services/GroupingsApiService.test.ts
[GROUPINGS-1637](https://uhawaii.atlassian.net/browse/GROUPINGS-1637)
- Fix extra tab space in the URL of the request form in About page
- Changed max-len ESLint to warn instead of error to be more lenient
- Made Navbar stick to the top of the page
- Set fetch functions in FetchService to use 'application/json' as default content type
=> Implement email stack trace

.github/workflows/ci.yml
[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1663)
-  Update CI workflow to run on Windows and MacOS
I didn't run any tests, because there is not point for this commit.
=> Update CI workflow to run on Windows and MacOS

.github/workflows/ci.yml
[GROUPINGS-1693](https://uhawaii.atlassian.net/browse/GROUPINGS-1693)
=> Downgrade macos-latest to macos-13 in ci.yml

ui/package.json, ui/tests/app/(index)/_components/LoginButton.test.tsx, ui/tests/components/layout/navbar/LoginButton.test.tsx, ui/tests/components/layout/navbar/MobileNavbar.test.tsx
[1687](https://uhawaii.atlassian.net/browse/GROUPINGS-1687)
-   Replace fireEvent with userEvent in Jest tests
=> Replace fireEvent with userEvent in Jest tests

ui/.eslintrc.json, ui/.prettierrc, ui/package.json, ui/src/actions/email.ts, ui/src/app/_components/footer/footer.tsx, ui/src/app/about/_components/general-info-section.tsx, ui/src/app/about/_components/technical-info-section.tsx, ui/src/app/about/_components/what-happens-if-section.tsx, ui/src/app/feedback/_components/error-alert.tsx, ui/src/app/feedback/_components/feedback-form.tsx, ui/src/app/feedback/_components/success-alert.tsx, ui/src/app/feedback/page.tsx, ui/src/app/layout.tsx, ui/src/components/ui/alert.tsx, ui/src/components/ui/form.tsx, ui/src/components/ui/input.tsx, ui/src/components/ui/label.tsx, ui/src/components/ui/select.tsx, ui/src/components/ui/textarea.tsx, ui/tests/app/about/_components/general-info-section.test.tsx, ui/tests/app/about/_components/technical-info-section.test.tsx, ui/tests/app/about/_components/what-happens-if-section.test.tsx, ui/tests/app/feedback/_components/error-alert.test.tsx, ui/tests/app/feedback/_components/feedback-form.test.tsx, ui/tests/app/feedback/_components/success-alert.test.tsx, ui/tests/app/feedback/page.test.tsx
[Ticket 1629](https://uhawaii.atlassian.net/browse/GROUPINGS-1629)
- Set "printWidth" to 120 in .prettierrc
- Simplify About page component tests
=> Create Feedback page

ui/src/app/globals.css, ui/src/components/ui/button.tsx
[1686](https://uhawaii.atlassian.net/browse/GROUPINGS-1686)
-   Add missing hover CSS animation to button.tsx
=> Add missing hover CSS animation to button.tsx

ui/package.json
[Ticket](Insert Link Here)
-   Update Next version
=> Update Next version

ui/tests/app/(home)/_components/after-login.test.tsx
[GROUPINGS-1736](https://uhawaii.atlassian.net/jira/software/c/projects/GROUPINGS/boards/18?assignee=712020%3Ad0e5c67f-f1f1-44a0-b5c9-282af528541e&selectedIssue=GROUPINGS-1736)
-   [X] Unit Tests Passed
-   [X] Integration Tests Passed
-   [X] General Visual Inspection
=> Removed unnecessary jest tests that failed if an admin/owner's membership/groupings count is 0

ui/src/app/globals.css, ui/src/components/ui/button.tsx
[GROUPINGS-1776](https://uhawaii.atlassian.net/browse/GROUPINGS-1776)
=> Update CSS for buttton.tsx

ui/src/components/layout/navbar/navbar.tsx, ui/src/components/modal/api-error-modal.tsx, ui/tests/app/_components/modal/api-error-modal.test.tsx
[Ticket 627](https://uhawaii.atlassian.net/browse/GROUPINGS-627)
- Link to Feedback page for the link and Report button
- Remove useHistory related code and add param to InfoModal
- Add tests
- Fix tests - don't check if Feedback page appears
- Remove React Router dependency
- Refactor as ApiErrorModal and remove from nav bar
- Change content to match ApiErrorModal
- Fix tests 
-   [ ] Integration Tests Passed (N/A)
=> Create the ApiErrorModal

ui/src/components/table/groupings-table-skeleton.tsx, ui/src/components/table/groupings-table.tsx, ui/src/components/table/table-element/ grouping-description-cell.tsx, ui/src/components/table/table-element/ grouping-name-cell.tsx, ui/src/components/table/table-element/grouping-path-cell.tsx, ui/src/components/table/table-element/groupings-table-columns.tsx, ui/src/components/table/table-element/tooltip-on-truncate.tsx, ui/tests/components/table/groupings-table.test.tsx, ui/tests/components/table/table-element/grouping-description-cell.test.tsx, ui/tests/components/table/table-element/grouping-name-cell.test.tsx
[Ticket1832](https://uhawaii.atlassian.net/browse/GROUPINGS-1832)
-   Commit 1:Refactor The GroupingsTable
=> Refactor The GroupingsTable

ui/src/lib/actions.ts, ui/src/lib/fetchers.ts, ui/src/lib/http-client.ts
[GROUPINGS-1795](https://uhawaii.atlassian.net/browse/GROUPINGS-1795)
-   Update comments
=> Remove & ApiError return type

ui/src/app/feedback/_components/feedback-form.tsx, ui/src/lib/actions.ts, ui/tests/lib/actions.test.ts
[GROUPINGS-1856](https://uhawaii.atlassian.net/browse/GROUPINGS-1856)
-   None
=> Santize parameters in actions.ts with Zod

ui/src/app/(home)/_components/announcements.tsx, ui/src/app/(home)/page.tsx, ui/src/app/groupings/[groupingPath]/_components/description-form.tsx, ui/src/app/groupings/[groupingPath]/_components/side-nav.tsx, ui/src/app/layout.tsx, ui/src/components/table/groupings-table-skeleton.tsx, ui/src/components/table/table-element/tooltip-on-truncate.tsx, ui/src/components/ui/alert-dialog.tsx, ui/src/components/ui/alert.tsx, ui/src/components/ui/button.tsx, ui/src/components/ui/input.tsx, ui/src/components/ui/select.tsx, ui/src/components/ui/textarea.tsx, ui/src/components/ui/tooltip.tsx, ui/tests/app/(home)/_components/announcements.test.tsx
[GROUPINGS-1858](https://uhawaii.atlassian.net/browse/GROUPINGS-1858)
-   Update test for announcement.tsx
=> Fix minor CSS issues

ui/src/components/layout/navbar/dept-account-icon.tsx
[Ticket 1835](https://uhawaii.atlassian.net/browse/GROUPINGS-1835)
=> Change school icon size

ui/src/app/groupings/[groupingPath]/_components/export-dropdown.tsx, ui/src/app/groupings/[groupingPath]/layout.tsx, ui/src/components/ui/button.tsx, ui/src/components/ui/spinner.tsx, ui/src/lib/actions.ts, ui/src/lib/http-client.ts, ui/tests/app/groupings/[groupingPath]/_components/export-dropdown.test.tsx, ui/tests/lib/actions.test.ts
[1851](https://uhawaii.atlassian.net/browse/GROUPINGS-1851)
-   Implement Export Button
-   [X] Unit Tests Passed
-   [X] General Visual Inspection
=> Implement Export Button

ui/.env, ui/src/app/feedback/_components/feedback-form.tsx, ui/src/lib/actions.ts, ui/tests/app/feedback/_components/feedback-form.test.tsx
[1845](https://uhawaii.atlassian.net/browse/GROUPINGS-1845)
-   Add a maximum character limit for the feedback text area
=> Add a maximum character limit for the feedback text area

ui/uh-groupings-ui-3-0-overrides.skeleton.properties
=> Restores deleted skeleton.properties file

ui/src/app/groupings/[groupingPath]/layout.tsx, ui/src/lib/fetchers.ts, ui/tests/app/groupings/[groupingPath]/layout.test.tsx, ui/tests/lib/fetchers.test.ts
[1943](https://uhawaii.atlassian.net/browse/GROUPINGS-1943)
-   Manage Grouping: Handle not found and access denied errors
=> Manage Grouping: Handle not found and access denied errors

ui/src/app/groupings/[groupingPath]/layout.tsx, ui/src/lib/fetchers.ts, ui/tests/app/groupings/[groupingPath]/layout.test.tsx, ui/tests/lib/fetchers.test.ts
Reverts uhawaii-system-its-ti-iam/uh-groupings#128
=> Revert "Manage Grouping: Handle not found and access denied errors"

.gitignore, ui/.env, ui/src/app/groupings/[groupingPath]/@tab/_components/grouping-actions.tsx, ui/src/app/groupings/[groupingPath]/@tab/_components/preference.tsx, ui/src/app/groupings/[groupingPath]/@tab/_components/sync-destinations.tsx, ui/src/app/groupings/[groupingPath]/@tab/actions/page.tsx, ui/src/app/groupings/[groupingPath]/@tab/preferences/page.tsx, ui/src/app/groupings/[groupingPath]/@tab/sync-destinations/page.tsx, ui/src/components/modal/dynamic-modal.tsx, ui/src/components/ui/spinner.tsx, ui/src/components/ui/switch.tsx, ui/src/lib/actions.ts, ui/src/lib/messages.ts, ui/src/lib/types.ts, ui/tests/app/groupings/[groupingPath]/@tab/_components/grouping-action.test.tsx, ui/tests/app/groupings/[groupingPath]/@tab/_components/preference.test.tsx, ui/tests/app/groupings/[groupingPath]/@tab/_components/sync-destinations.test.tsx, ui/tests/app/groupings/[groupingPath]/@tab/actions/page.test.tsx, ui/tests/app/groupings/[groupingPath]/@tab/preferences/page.test.tsx, ui/tests/app/groupings/[groupingPath]/@tab/sync-destinations/page.test.tsx, ui/tests/components/modal/dynamic-modal.test.tsx
[1749](https://uhawaii.atlassian.net/browse/GROUPINGS-1749?atlOrigin=eyJpIjoiMWY1MTkzZjUyNzQ4NGU3ZTgzYWE0NjU2NTIwNGRkZGQiLCJwIjoiaiJ9)
-   Begin implementing actions, preferences and sync destinations
=> Implements actions, preferences and sync destinations

ui/.eslintrc.json
[Groupings-1980](https://uhawaii.atlassian.net/jira/software/c/projects/GROUPINGS/boards/18?assignee=63d77dcbfb75f8568f5e8ab1&selectedIssue=GROUPINGS-1980)
-   Updated line max length to 170 in .eslintrc.json
=> Increase max line length rule in .eslintrc.json

.gitignore, ui/src/app/about/_components/general-info-section.tsx, ui/src/app/about/_components/image-item.tsx, ui/src/app/about/_components/question-item.tsx, ui/src/app/about/_components/what-happens-if-section.tsx, ui/src/app/globals.css, ui/src/components/uh-groupings-info.tsx, ui/tests/components/uh-groupings-info.test.tsx
[GROUPINGS-1878](https://uhawaii.atlassian.net/browse/GROUPINGS-1878)
- Apply the new component architecture to the About page
-   [X] Unit Tests Passed
-   [X] Integration Tests Passed
-   [X] General Visual Inspection
=> Apply the new component architecture to the About page

ui/src/lib/fetchers.ts, ui/tests/lib/fetchers.test.ts
[2039](https://uhawaii.atlassian.net/browse/GROUPINGS-2039?atlOrigin=eyJpIjoiNDQyMWFlMzZhODZiNGFmOWI5MDkxZjRkZGI1ZWNiYmUiLCJwIjoiaiJ9)
-   Update endpoint calls' URIs
=> Update URIs of endpoint calls
